In [1]:
import pandas as pd

In [3]:
ec = pd.read_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-19/E-Commerce-Sales/dashboard/archive/E-Commerce Sales Analytics.csv")

In [5]:
ec.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [7]:
ec.tail()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4995,14996,9/5/2035,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,9/6/2035,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,9/7/2035,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,9/8/2035,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,9/9/2035,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [9]:
ec.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

In [11]:
ec.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [15]:
ec['order_date'] = pd.to_datetime(ec['order_date'], format='mixed', dayfirst=True)

In [17]:
ec.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,2022-01-01,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,2022-02-01,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,2022-03-01,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,2022-04-01,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,2022-05-01,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

In [19]:
ec.tail()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
4995,14996,2035-05-09,1289,Clothing,West,2,371.74,0.27,COD,3,2.3,542.74
4996,14997,2035-06-09,1294,Beauty,North,3,553.67,0.14,COD,11,2.2,1428.47
4997,14998,2035-07-09,1450,Beauty,West,3,77.22,0.24,Wallet,6,3.4,176.06
4998,14999,2035-08-09,1903,Electronics,South,4,138.41,0.21,COD,4,2.8,437.38
4999,15000,2035-09-09,1214,Home,East,7,231.58,0.34,COD,5,3.9,1069.90

In [21]:
ec.to_csv("C:/Users/mathe/Documents/projetos/Analise de dados/projeto-19/E-Commerce-Sales/dashboard/archive/E-Commerce Sales Analytics 1.0 .csv")